<?php

declare(strict_types=1);

/**
 * @file
 * Provides a queue entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function queue_entity_theme(): array {
  return [
    'queue_entity' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for queue entity templates.
 *
 * Default template: queue-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the queue entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_queue_entity(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function queue_entity_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish queue entities.
      $storage = \Drupal::entityTypeManager()->getStorage('queue_entity');
      $queue_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($queue_entity_ids) as $queue_entity) {
        $queue_entity->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize queue entities.
      $storage = \Drupal::entityTypeManager()->getStorage('queue_entity');
      $queue_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($queue_entity_ids) as $queue_entity) {
        $queue_entity->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function queue_entity_user_predelete(UserInterface $account): void {
  // Delete queue entities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('queue_entity');
  $queue_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($queue_entity_ids)
  );
}
